ocve/urls.py
__author__ = 'Elliot'
from django.conf.urls import patterns, include, url

from annotationviews import *
from dbmi.uploader import newsourcefiles, posth
from views import *

urlpatterns = patterns('',
                       # DBMI
                       (r'^', include('ocve.dbmi.dbmi_urls')),

                       # UI URLS
                       (r'^browse/barview$', barview),
                       #(r'^correctsi/$', correctSourceInformation ),
                       (r'^browse/acview/(?P<acHash>[\d|\w]+)/$', acview),
                       (r'^browse/sourcejs/$', sourcejs),
                       url(r'^browse/$', browse, name='ocve_browse'),
                       url(r'^browse/pageview/(?P<id>\d+)/$',
                           ocvePageImageview, name='ocve_pageview'),
                       (r'^browse/pageview/(?P<id>\d+)/(?P<selectedregionid>\d+)/$',
                        ocvePageImageview),
                       (r'^browse/shelfmarkview/(?P<acHash>[\d|\w]+)/$',
                        shelfmarkview),
                       url(r'^browse/sourceinformation/(?P<id>\d+)/$',
                           sourceinformation, name='ocve_sourceinformation'),
                       url(r'^browse/workinformation/(?P<id>\d+)/$',
                           workinformation, name='ocve_workinformation'),
                       (r'^browse/serializeFilter/$', serializeFilter),
                       (r'^browse/resetFilter/$', resetFilter),
                       # Ajax url for annotation fetch
                       (r'^browse/getAnnotations/(?P<id>\d+)/$',
                        getAnnotations),

                       (r'^data/verifyImages/', verifyImages),
                       (r'^data/uploadOCVE/', uploadOCVE),

                       (r'^getBarRegions/(?P<id>\d+)/$', getBarRegions),
                       (r'^getBarRegions/(?P<id>\d+)/(?P<barid>\d+)/$',
                        getViewInPageRegions),
                       (r'^getGroupedBarRegions/(?P<id>\d+)/$',
                        getGroupedBarRegions),

                       # Annotation URLS
                       (r'^saveNote/$', saveNote),
                       (r'^deleteNote/(?P<id>\d+)$', deleteNote),
                       (r'^newsourcefiles/$', newsourcefiles),
                       (r'^getAnnotationRegions/(?P<id>\d+)/$',
                        getAnnotationRegions),
                       (r'^posth/$', posth),

                       # Ajax URLS for inline collections
                       (r'^ajax/inline-collections/$', ajaxInlineCollections),
                       (r'^ajax/change-collection-name/$',
                        ajaxChangeCollectionName),
                       (r'^ajax/add-collection/$', ajaxAddCollection),
                       (r'^ajax/add-image-to-collection-modal/$',
                        ajaxAddImageToCollectionModal),
                       (r'^ajax/add-image-to-collection/$',
                        ajaxAddImageToCollection),
                       (r'^ajax/delete-image-from-collection/$',
                        ajaxDeleteImageFromCollection),
                       (r'^ajax/delete-collection/$', ajaxDeleteCollection),

                       # User account management - required for OCVE UI
                       (r'^accounts/profile/$', user_profile),
                       (r'^accounts/',
                        include('registration.backends.default.urls')),
                       )

ocve/models.py
from django.db import models
from django.conf import settings
from models_generic import *

import hashlib

# Create your models here.


class BarSpine(models.Model):
    label = models.TextField(null=False, default="", blank=True, )
    bar = models.ForeignKey('Bar', blank=False, null=False, default=1 )
    #page = models.ForeignKey('Page', blank=False, null=False, default=1 )
    sourcecomponent = models.ForeignKey('SourceComponent', blank=False, null=False, default=1 )
    orderNo = models.IntegerField(null=True, blank=True,default=0 )
    source = models.ForeignKey('Source', blank=False, null=False, default=1 )
    implied=models.IntegerField(null=True, blank=True,default=0 )


def country_unicode(self):
    return self.country

Country.__unicode__=country_unicode
Country._meta.ordering = ["country"]


def archive_unicode(self):
    return self.name

Archive.__unicode__=archive_unicode
Archive._meta.ordering = ["name"]

def work_unicode(self):
    return self.label

Work.__unicode__=work_unicode
Work._meta.ordering = ["orderno"]

def workComponent_unicode(self):
    return self.label

WorkComponent.__unicode__=workComponent_unicode
WorkComponent._meta.ordering = ["orderno"]

def source_unicode(self):
    return self.label
Source._meta.ordering = ["label"]

Source.__unicode__=source_unicode

def sourcet_unicode(self):
    return self.type

SourceType.__unicode__=sourcet_unicode

def sourcect_unicode(self):
    return self.type

SourceComponentType.__unicode__=sourcect_unicode

def WorkInformation_unicode(self):
    return str(self.id)

WorkInformation.__unicode__=WorkInformation_unicode

def PrintingMethod_unicode(self):
    return self.method

PrintingMethod.__unicode__=PrintingMethod_unicode

def SourceComponent_unicode(self):
    out=''
#    works=Work.objects.filter(workcomponent__sourcecomponent_workcomponent__sourcecomponent=self)
#    for w in works:
#        out+=w.label+" "
    out +=self.label
    return out

def getWorkComponentLabel(self):
    label=''
    try:
        wc=WorkComponent.objects.get(sourcecomponent_workcomponent__sourcecomponent=self)
        label=wc.label
    except ObjectDoesNotExist:
        pass
    except MultipleObjectsReturned:
        pass
    return label

SourceComponent.getWorkComponentLabel=getWorkComponentLabel
SourceComponent.__unicode__=SourceComponent_unicode


def page_unicode(self):
    return self.label

#class Page(Page):
 #     class Meta:
  #      ordering = ["orderno"]

Page.__unicode__=page_unicode
Page._meta.ordering = ["orderno"]






#PageImage._meta.order_with_respect_to='page'

def barregion_unicode(self):
    label=''
    for b in self.bar.all():
        label+=b.barlabel
    return label

#class BarRegion(BarRegion):
 #     class Meta:
  #      ordering = ["bar.barnumber"]

BarRegion.__unicode__=barregion_unicode
#BarRegion._meta.ordering = ["bar.barnumber"]

def opus_unicode(self):
    return str(self.opusno)

Opus.__unicode__=opus_unicode
Opus._meta.ordering = ["opusno"]

def keyPitch_unicode(self):
    return self.keypitch

keyPitch.__unicode__=keyPitch_unicode
keyPitch._meta.ordering = ["orderno"]

#class toneNote(toneNote):

def keyMode_unicode(self):
    return self.keymode

keyMode.__unicode__=keyMode_unicode
keyMode._meta.ordering = ["keymode"]

def bar_unicode(self):
    return self.barlabel

#class Bar(Bar):

Bar.__unicode__=bar_unicode
Bar._meta.ordering = ["barnumber","barlabel"]

def pub_unicode(self):
    return self.publisher
Publisher.__unicode__=pub_unicode
Publisher._meta.ordering=["publisher"]

def ins_unicode(self):
    return self.instrument

Instrument.__unicode__=ins_unicode
Instrument._meta.ordering=["instrument"]

def genre_unicode(self):
    return self.genre
Genre.__unicode__=genre_unicode
Genre._meta.ordering = ["genre"]

def workc_unicode(self):
    return self.label
WorkCollection.__unicode__=workc_unicode


#Tree._meta.ordering=["level","orderNo"]

def treetype_unicode(self):
    return self.type
TreeType.__unicode__=treetype_unicode

def ac_unicode(self):
    return self.accode

AcCode.__unicode__=ac_unicode

def save(self, *args, **kwargs):
    self.accode_hash = hashlib.md5(self.accode.encode('UTF-8')).hexdigest()
    super(AcCode, self).save(*args, **kwargs)

AcCode.save = save


def dedicatee_unicode(self):
    return self.dedicatee

Dedicatee.__unicode__=dedicatee_unicode

class EditStatus(models.Model):
    status = models.CharField(max_length=255, null=False, default="NONE", blank=True, )

def sourcestatus_unicode(self):
    return self.status

EditStatus.__unicode__=sourcestatus_unicode
EditStatus._meta.ordering = ["id"]

class SourceLegacy(models.Model):
     cfeoKey = models.IntegerField(null=True, blank=True,default=0 )
     witnessKey = models.IntegerField(null=True, blank=True,default=0 )
     source = models.ForeignKey('Source', blank=False, null=False, default=1 )
     sourceDesc = models.TextField(null=False, default="", blank=True, )
     editstatus =  models.ForeignKey('EditStatus', blank=False, null=False, default=1, )
     mellon = models.BooleanField(default=False, null=False, blank=False)
     needsBarLines = models.BooleanField(default=False, null=False, blank=False)

class PageLegacy(models.Model):
    ocveKey = models.IntegerField(null=True, blank=True, )
    cfeoKey = models.IntegerField(null=True, blank=True, )
    filename = models.TextField(null=False, default="", blank=True, )
    storageStructure = models.TextField(null=False, default="", blank=True, )
    pageimage = models.ForeignKey('PageImage', blank=False, null=False, default=1, )
    cropCorrected = models.IntegerField(null=True, blank=True, default=0)
    editstatus =  models.ForeignKey('EditStatus', blank=False, null=False, default=1, )
    jp2=models.CharField(max_length=255, null=False, default="UNVERIFIED", blank=True, )

    class Meta:
        verbose_name = 'Page Legacy'
        verbose_name_plural = 'Page Legacy'

#For brand new images for brand new sources
#Moved to normal structure after audit

class NewPageImage(models.Model):
    surrogate = models.IntegerField(null=True, blank=True, )
    versionnumber = models.IntegerField(null=True, blank=True, )
    permission = models.BooleanField(default=False, null=False, blank=False, )
    permissionnote = models.CharField(max_length=255, null=False, default="", blank=True, )
    height = models.IntegerField(null=True, blank=True, )
    width = models.IntegerField(null=True, blank=True, )
    filename = models.CharField(max_length=255, null=False, default="", blank=True, )
    startbar = models.CharField(max_length=255, null=False, default="", blank=True, )
    endbar = models.CharField(max_length=255, null=False, default="", blank=True, )
    corrected = models.IntegerField(null=True, blank=True, default=0)
    linked = models.IntegerField(null=True, blank=True, default=0) #>0 if it is saved in pages/page images
    source = models.ForeignKey('NewSource', blank=False, null=False, default=1, )
    barsequences = generic.GenericRelation(BarSequence, null=True, blank=True)

    class Meta:
        verbose_name = 'NewPageImage'
        verbose_name_plural = 'NewPageImages'

class NewSource(models.Model):
    label = models.TextField(null=False, default="", blank=True, )
    library = models.TextField(null=False, default="", blank=True, )
    copyright = models.TextField(null=False, default="", blank=True, )
    sourcecode=models.CharField(max_length=255, null=False, default="", blank=True, )
    sourcecreated = models.IntegerField(null=False, blank=False,default=0 )

def newSource_unicode(self):
    label="no library given"
    if self.library is not None:
        label=self.library
    if self.sourcecode is not None:
        label=label+" - "+self.sourcecode
    return label

NewSource.__unicode__= newSource_unicode


class NewSourceInformation(models.Model):
    platenumber = models.CharField(max_length=255, null=False, default="", blank=True, )
    locationsimilarcopies = models.TextField(null=False, default="", blank=True, )
    reprints = models.TextField(null=False, default="", blank=True, )
    seriestitle = models.CharField(max_length=255, null=False, default="", blank=True, )
    copyright = models.CharField(max_length=255, null=False, default="", blank=True, )
    contentssummary = models.CharField(max_length=255, null=False, default="", blank=True, )
    contents = models.TextField(null=False, default="", blank=True, help_text=ur'''Edition text''', )
    shelfmark = models.CharField(max_length=255, null=False, default="", blank=True, )
    notes = models.TextField(null=False, default="", blank=True, )
    datepublication = models.CharField(max_length=255, null=False, default="", blank=True, )
    leaves = models.IntegerField(null=True, blank=True, )
    sourcecode = models.CharField(max_length=255, null=False, default="", blank=True, )
    title = models.TextField(null=False, default="", blank=True, )
    publicationtitle = models.TextField(null=False, default="", blank=True, )
    imagesource = models.CharField(max_length=255, null=False, default="", blank=True, )
    platenumber = models.CharField(max_length=255, null=False, default="", blank=True, )
    additionalInformation=models.TextField(null=False, default="", blank=True, )
    keyFeatures=models.TextField(null=False, default="", blank=True, )
    volume = models.CharField(max_length=255, null=False, default="", blank=True, )
    source = models.ForeignKey('NewSource', blank=False, null=False, default=1, )
    publisher = models.ForeignKey('Publisher', blank=False, null=False, default=1, )
    archive = models.ForeignKey('Archive', blank=False, null=False, default=1, )

ocve/forms.py
__author__ = 'Elliot'
from django.forms import *
from django import forms
from models import *
from tinymce.widgets import TinyMCE

class WorkForm(ModelForm):

    class Meta:
        model = Work
        exclude = ('workinformation',)

class NewSourceForm(ModelForm):
     class Meta:
         model = NewSource
         exclude = ('sourcecreated',)

class SourceForm(ModelForm):

    class Meta:
        model = Source
        exclude = ('',)

class SourceComponentForm(ModelForm):
    class Meta:
        model = SourceComponent
        exclude = ('overridelabel',)

class WorkInformationForm(ModelForm):

    class Meta:
        model = WorkInformation
        exclude = ('',)

class WorkComponentForm(ModelForm):

    class Meta:
        model = WorkComponent
        exclude = ('',)

WorkComponentFormset=modelformset_factory(WorkComponent,exclude=())

class SourceInformationForm(ModelForm):

    class Meta:
        model = SourceInformation
        exclude = ('',)

class AnnotationForm(ModelForm):

    class Meta:
        model = Annotation
        fields = ['id','notetext','noteregions','pageimage','user']
        widgets = { 'id':HiddenInput(),
                    'user':HiddenInput(),
                    'pageimage':HiddenInput(),
                    'noteregions':HiddenInput()
        }



ocve/views.py
# Create your views here.


from dbmi.dbmiviews import *
from uiviews import *

IIP_URL = settings.IIP_URL
IMAGE_SERVER_URL = settings.IMAGE_SERVER_URL

#Image format for all uploaded pages
#Forced rather than detected because only tifs should be uploaded
UPLOAD_EXTENSION = '.tif'

#Error reporting template
errorPage = 'error.html'





def uploadOCVE(request):
    log = upload(request)
    return HttpResponse(log)

@csrf_exempt
def getBarRegions(request, id):
    geos = getGeoJSON(id)
    return render_to_response('geojson.html', {'geoRegions': geos, 'grouped': 0})



def getViewInPageRegions(request, id, barid):
    geos = getViewInPageJSON(id,barid)
    return render_to_response('geojson.html', {'geoRegions': geos, 'grouped': 0})


@csrf_exempt
def getGroupedBarRegions(request, id):
    geos = getGeoJSON(id)
    return render_to_response('geojson.html', {'geoRegions': geos, 'grouped': 1})




def updateSourceComponent(request):
    page_id=int(request.POST['page_id'])
    component_id=int(request.POST['sourcecomponent_id'])
    p=Page.objects.get(id=page_id)
    sc=SourceComponent.objects.get(id=component_id)
    if p is not None and sc is not None:
        p.sourcecomponent=sc
        p.save()
    return HttpResponseRedirect("/ocve/structure/18153/#"+str(page_id))




def user_profile(request):
    if request.user and request.user.id:
        annotations=Annotation.objects.filter(ocve_user_id=request.user.id)

    return render_to_response("registration/user_profile.html",
            {'annotations':annotations},
        context_instance=RequestContext(request))

ocve/templates/dbmi/bareditor.html
<!DOCTYPE html>
<html>
<head>

    <title>DBMI Bareditor</title>

    <script type="text/javascript" src="{{ STATIC_URL }}vendor/jquery/dist/jquery.min.js"></script>

    <script src="{{ STATIC_URL }}vendor/OpenLayers/lib/OpenLayers.js"></script>
    <script src="{{ STATIC_URL }}vendor/OpenLayers/lib/OpenLayers/BaseTypes/Class.js"></script>
    <script src="{{ STATIC_URL }}vendor/OpenLayers/lib/OpenLayers/Util.js"></script>
    <script src="{{ STATIC_URL }}vendor/OpenLayers/lib/OpenLayers/Events.js"></script>
    <script src="{{ STATIC_URL }}vendor/OpenLayers/lib/OpenLayers/Tween.js"></script>
    <script src="{{ STATIC_URL }}vendor/OpenLayers/lib/OpenLayers/Console.js"></script>
    <script src="{{ STATIC_URL }}vendor/OpenLayers/lib/OpenLayers/Lang.js"></script>
    <script src="{{ STATIC_URL }}vendor/OpenLayers/lib/OpenLayers/Layer/Grid.js"></script>
    <script src="{{ STATIC_URL }}vendor/OpenLayers/lib/OpenLayers/Layer/Zoomify.js"></script>

    <!-- Irregular transform from Miguel Vieria's image annnotator https://github.com/kcl-ddh/openlayers-image-annotation/ -->
    <script type="text/javascript" src="{{ STATIC_URL }}javascripts/annotator-helper.js"></script>

    <link rel="stylesheet" href="{{ STATIC_URL }}vendor/OpenLayers/theme/default/style.css" type="text/css">
    <link rel="stylesheet" href="{{ STATIC_URL }}custom_css/bareditor.css" type="text/css">
    {% if mode == 1 %}
        <!-- crop correct mode-->
        <script src="{{ STATIC_URL }}javascripts/cropcorrect.js"></script>
    {% else %}
        <script src="{{ STATIC_URL }}javascripts/bareditor.js"></script>
    {% endif %}

    <script type="text/javascript">

        var zoomify_width = {{pageimage.width}};   // 3368;
        var zoomify_height = {{pageimage.height}};  //4210;
        {% autoescape off %}
            pageID ={{ pageimage.id }} //77557 ;
            var zoomify_url = "{{ zoomifyURL }}"
            //Ajax URL to get bar regions, switches between grouped and uoverngrouped geometries
            var regionURL = "{{regionURL}}"
        {% endautoescape %}
        startX = 0;
        startY = 0;
        endX = 0;
        endY = 0;
        var map, zoomify;
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('p.box').click(function (e) {
                selectFeature.unselectAll();
                var barid=$(e.target).html();
                $(e.target).data("regionid")
                populateBarForm(barid,$(e.target).data("regionid"),$(e.target).data("anomaly"));
                if (barid ==0){
                    barid='zero';
                }
                var select=vlayer.getFeaturesByAttribute('label',barid);
                if (select.length > 0){
                    selectFeature.select(select[0]);
                }
            });
        });
    </script>
</head>
<body>
<div>
    <ul class="barnav">
        {% if prev %}
            <li class="prev"><a href="/ocve/editbars/{{ prev.id }}"><< {{ prev.page.label }}</a></li>
        {% endif %}
        <li><a href="/ocve/sourceview/{{ page.sourcecomponent.source.id }}/">Back
            to {{ page.sourcecomponent.source.getOpusLabel }}</a></li>
        {% if next %}
            <li class="next"><a href="/ocve/editbars/{{ next.id }}">{{ next.page.label }} >></a></li>
        {% endif %}
    </ul>

    {% autoescape off %}
        <h1> {{ page.sourcecomponent.source.label }} ({{ page.sourcecomponent.source.getAcCode }}),
            page {{ page.label }} bs. {{ pageimage.startbar }}-{{ pageimage.endbar }}</h1>
    {% endautoescape %}
    <p>{{ zoomifyURL }}::{{ pl.storageStructure }}</p>

    {% if mode == 1 %}

        <p>Click on the orange bars (one click will select them all.) You must click first to initialize the tool. Then
            click the 'drag' control button (<img
                    src="{{ STATIC_URL }}vendor/OpenLayers/theme/default/img/pan_off.png"/>) Move the grouped bars so
            that they line up with the uncropped image, then press save. The change
            will be applied to all bar regions</p>
        <p><a href="/ocve/editbars/{{ pageimage.id }}/">Edit individual bars</a></p>
    {% else %}
        {% if request.session.sourceViewMode %}
            <a href="/ocve/sourceviews/{{ request.session.sourceViewMode }}/">Back to source list</a>
        {% endif %}
        <!--<p><a rel="lightbox" href="/static/html/helpfiles/bareditorhelp.html">Help</a></p>-->
        <p><a href="/ocve/cropCorrect/{{ pageimage.id }}/">Correct Cropping</a></p>

    {% endif %}
</div>
<div class="rightFrame">
    {% if mode != 1 %}
        <form method="POST" action="/ocve/updateBarNumber/" id="numberForm">
            {% csrf_token %}
            <input id="regionID" type="hidden" name="id" value="0">
            <input id="barNumber" type="text" name="barNumber" value="0"/>
            <input title="Anomalous bar?" id="anomaly" name="anomaly" type="checkbox" value="1">
            <input type="Submit" value="Change">
            <button type="Submit"  name="Delete" value="1">Delete</button>
        </form>
        <form method="POST" action="/ocve/reorderBars/" id="reorderForm">
            {% csrf_token %}
            <input id="pageid" type="hidden" name="pageid" value="{{ pageimage.id }}">

            <input type="Submit" value="Reassign all bar numbers">
        </form>
        <input type="button" value="Fix System" id="smoothTest">
    {% endif %}
    <p>Bars on this page: </p>
    {% autoescape off %}
        <p class="box">{{ regionString }}</p>
    {% endautoescape %}
    <p>Page Status</p>

    <form action="/ocve/updateStatus/" method="POST">
        <input id="page_id" type="hidden" name="page_id" value="{{ pageimage.id }}">
        {% for legacy in pageimage.pagelegacy_set.all %}
            <select name="status">
                {% for stat in statuses %}
                    <option {% if legacy.editstatus.id == stat.id %}selected="selected"{% endif %}
                            value="{{ stat.id }}">{{ stat.status }}</option>
                {% endfor %}
            </select>
        {% endfor %}
        <input id="correctsubmit" type="submit" name="correct" value="Update status">
    </form>

    <p>Keys: </p>
    <ul>
        <li>Select Next Bar: <strong>n</strong></li>
        <li>Unselect all: <strong>esc</strong></li>
        <li>Fix System: <strong>CTRL+ALT+F</strong></li>
        <!-- <li></li>-->
    </ul>
    <p> Jump to page</p>
    <ul>
        {% for p in pages %}
            <li><a href="/ocve/editbars/{{ p.id }}/">{{ p.textlabel }}</a></li>
        {% endfor %}
    </ul>

</div>
<div id="map"></div>

</body>
</html>

ocve/templates/dbmi/correctview.html
<!DOCTYPE html>
<html>
<head>
    <title>Sources</title>
    <style type="text/css">
        .corrected {
            text-decoration: line-through;
        }
    </style>
</head>
<body>
<a href="/ocve/dbmi/"> Back to DBMI</a>
{% if sources %}
    <h2>{{ title }}</h2>
    <h3>Source counts by edit status</h3>
    <ul>
        {% for s,count in sourcecounts.items %}
            <li>{{ s }}: {{ count }}</li>
        {% endfor %}
    </ul>
    <form action="#" method="POST">
        <input type="hidden" name="ordermode" value="1">
        <input type="hidden" name="filtercomplete" value="{{ filterComplete }}">
        <input type="submit" value="Order by opus number (default)">
    </form>
    {% if filterComplete == 0 %}
        <form action="#" method="POST">
            <input type="hidden" name="ordermode" value="{{ ordermode }}">
            <input type="hidden" name="filtercomplete" value="1">
            <input type="submit" value="Filter out sources marked as complete">
        </form>
    {% else %}
        <form action="#" method="POST">
            <input type="hidden" name="ordermode" value="{{ ordermode }}">
            <input type="hidden" name="filtercomplete" value="0">
            <input type="submit" value="Show all">
        </form>
    {% endif %}
    <form action="#" method="POST">
        <input type="hidden" name="ordermode" value="2">
        <input type="hidden" name="filtercomplete" value="{{ filterComplete }}">
        <input type="submit" value="Order by edit status">
    </form>
    <ol>
        {% autoescape off %}
            {% for s in sources %}
                <li><a href="/ocve/sourceview/{{ s.id }}/">{{ s.getAcCode }}: {{ s.getOpusLabel }}
                    <strong>{{ s.getEditStatus.status }}</strong>
                    {% comment %}{% for legacy in s.sourcelegacy_set.all %}
                        <strong>{{ legacy.editstatus.status }}</strong>
                    {% endfor %}{% endcomment %}
                </a></li>
            {% endfor %}
        {% endautoescape %}
    </ol>

{% endif %}
{% if source %}
    <a href="/ocve/sourceviews/{{ request.session.sourceViewMode }}/">Back to list</a>
    <h1>{{ source.getOpusLabel }}</h1>
    <p><a href="/ocve/sourceeditor/{{ source.id }}/">Edit Source</a></p>
    <p>When you have finished editing all pages, click the box below to record that this source has been corrected</p>
    <form action="/ocve/updateStatus/" method="POST">
        <input id="source_id" type="hidden" name="id" value="{{ source.id }}">
        {% for legacy in source.sourcelegacy_set.all %}
            {{ legacy.witnessKey }}
            <select name="status">
                {% for stat in statuses %}
                    <option {% if legacy.editstatus.id == stat.id %}selected="selected"{% endif %}
                            value="{{ stat.id }}">{{ stat.status }}</option>
                {% endfor %}
            </select>
        {% endfor %}
        <label for="andpages">Apply to source's pages</label>
        <input type="checkbox" id="andpages" name="andpages" value="1">
        <input id="correctsubmit" type="submit" name="correct" value="Update status">
    </form>
    <ol>
        {% for p in pages %}
            <li>
            ({{ p.id }}) <a href="/ocve/editbars/{{ p.id }}/">{{ p.page.label }} {{ p.startbar }}-{{ p.endbar }}</a>
            ({{ p.page.orderno }})
                {% for legacy in p.pagelegacy_set.all %}
                    {% comment %}<p>Filename: {{ legacy.filename }}</p>
                    <p>Storage:  {{ legacy.storageStructure }}</p>{% endcomment %}
                    <strong>{{ legacy.editstatus.status }}</strong>
                {% endfor %}
            </li>
        {% endfor %}
    </ol>

{% endif %}
</body>
</html>

ocve/templates/dbmi/importresult.html
<!DOCTYPE html>
<html>
<head>
    <title>Import Result</title>
</head>
<body>
<h1>{{ result }}</h1>
Return to <a href="/ocve/editspine/{{ work.id }}/">{{ work }}</a>
</body>
</html>

ocve/templates/dbmi/posth.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
{% for p in posths %}
<h1>{{ p.label }}</h1>
<h2>work components</h2>
<ul>
    {% for wc in p.workcomponent_set.all %}
        <li>{{ wc.label }}</li>
    {% endfor %}
</ul>

{% endfor %}
</body>
</html>

ocve/templates/dbmi/sourcesbywork.html
<!DOCTYPE html>
<html>
<head>
    <title>Source by opus</title>
</head>
<body>
<h1>Sources by work</h1>
<a href="/ocve/dbmi">return to DBMI</a>
{%   for w in works %}
<h1>{{ w.label }}</h1>
    <a href="/admin/ocve/workinformation/{{ w.workinformation.id }}/">Edit information</a>
    <h3>CFEO Information</h3>
<dl>
<dt>General Information</dt>
<dd>{{ w.workinformation.generalinfo }}</dd>
<dt>Relevant Manuscripts</dt>
<dd>{{ w.workinformation.relevantmanuscripts }}</dd>
<dt>Analysis</dt>
<dd>{{ w.workinformation.analysis }}</dd>
</dl>
    <h3>OCVE Information</h3>

    <p>{% autoescape off %}
        {{ w.workinformation.OCVE }}
    {% endautoescape %}
    </p>
    <ul>
    {% for s in w.getSources %}
        <li><a href="/ocve/sourceeditor/{{ s.id }}/" title="{{ s.label }}">{{ s.getAcCode }}</a> (shelfmark {{ s.getSourceInformation.shelfmark }})</li>
       {% endfor %}
    </ul>
{% endfor %}
</body>
</html>